name: Strapi CI

on:
  push:
    branches: [ "master" ] # Updated to use "master" as the default branch
  pull_request:
    branches: [ "master" ] # Updated to use "master" as the default branch

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Use Node.js 18.x for Strapi

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install # To generate package-lock.json if it doesn't exist
    - run: npm run build
    - name: Start Strapi Server
      run: npm start
    - run: npm test
