name: Strapi CI

on:
  push:
    branches: [ "master" ] # Change to your default branch name
  pull_request:
    branches: [ "master" ] # Change to your default branch name

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # Ensure Node.js 16.x is used for Strapi

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run build
    - name: Start Strapi Server
      run: npm start
    - run: npm test
